run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/mattermost/mattermost-plugin-github
  govet:
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    # - errcheck
    # - goconst
    - gocritic
    - gofmt
    - goimports
    # - gosec
    - gosimple
    - govet
    - ineffassign
    # - misspell
    - nakedret
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: server/manifest.go
      linters:
        - deadcode
        - unused
        - varcheck
    - path: server/configuration.go
      linters:
        - unused
    - linters:
        - revive
      text: unused-parameter
    - linters:
        - revive
      text: var-naming
    - linters:
        - revive
      text: error-strings
    - path: _test\.go
      linters:
        - bodyclose
        - goconst
        - scopelint # https://github.com/kyoh86/scopelint/issues/4