[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/google/go-github"
  revision = "fe267204ab6dc819efe645730b03eb44cbca91f1"

[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  version = "~5.6.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.0"
